import {
  FileText, FolderCheck, BarChart3, Receipt, BadgeCheck, CreditCard,
  Globe, TrendingUp, AlertTriangle, ScrollText, Scale, Users,
  ClipboardList, HeartHandshake, DollarSign, FileCog, Calculator,
  GitCompare, IndianRupee, BookOpen, FileCheck, ArrowLeftRight,
  Banknote, UserCheck, Anchor, Building2, Lock, Layers, Fingerprint,
  PieChart, Sparkles, ScanLine, Calendar, Shield, Database, FileSignature, Landmark
} from 'lucide-react';

export interface FormModuleMetadata {
  id: string;
  label: string;
  subLabel: string;
  description: string;
  icon: any;
  color: string;
  bgColor: string;
  badge?: string;
  isNew?: boolean;
}

export const DIRECT_TAX: FormModuleMetadata[] = [
  { id:'itr1', label:'ITR-1 (Sahaj)', subLabel:'ITR-1', description:'For salaried individuals with income up to Rs 50 Lakhs. Auto-fills from salary slip and Form 16.', icon:FileText, color:'text-purple-400', bgColor:'bg-purple-500/20', badge:'Annual Return' },
  { id:'itr2', label:'ITR-2', subLabel:'ITR-2', description:'For individuals/HUFs with capital gains, foreign assets, or multiple properties (no business income).', icon:FileText, color:'text-purple-400', bgColor:'bg-purple-500/20', badge:'Annual Return' },
  { id:'itr34', label:'ITR-3 & ITR-4 (Sugam)', subLabel:'ITR-3/4', description:'ITR-3 (Proprietors/Professionals) + ITR-4 Presumptive u/s 44AD/ADA. Full slab tax computation.', icon:FileText, color:'text-purple-400', bgColor:'bg-purple-500/20', badge:'Annual Return', isNew:true },
  { id:'itr5', label:'ITR-5', subLabel:'ITR-5', description:'For LLPs, Partnership Firms, and AOPs/BOIs. Auto-fills partner profit sharing ratios.', icon:FileText, color:'text-purple-400', bgColor:'bg-purple-500/20', badge:'Annual Return' },
  { id:'itr6', label:'ITR-6', subLabel:'ITR-6', description:'Mandatory annual return for all corporate Companies. Compiles Schedule III sheets.', icon:FileText, color:'text-purple-400', bgColor:'bg-purple-500/20', badge:'Annual Return' },
  { id:'itr7', label:'ITR-7', subLabel:'ITR-7', description:'For Trusts, political parties, colleges, and NGOs u/s 139(4A/4B/4C/4D).', icon:FileText, color:'text-purple-400', bgColor:'bg-purple-500/20', badge:'Annual Return' },
  { id:'form3ca', label:'Form 3CA (Audit Report - Other Acts)', subLabel:'Form 3CA', description:'Audit Report u/s 44AB for entities already audited under another Act such as Companies Act.', icon:FolderCheck, color:'text-teal-400', bgColor:'bg-teal-500/20', badge:'Tax Audit' },
  { id:'form3cb', label:'Form 3CB (Audit Report - 44AB)', subLabel:'Form 3CB', description:'Audit Report u/s 44AB for sole proprietorships or partnerships not audited under another law.', icon:FolderCheck, color:'text-teal-400', bgColor:'bg-teal-500/20', badge:'Tax Audit' },
  { id:'form3cd', label:'Form 3CD (44 Clauses Statement)', subLabel:'Form 3CD', description:'44-clause statement of particulars for Tax Audit. AI scanner auto-checks every clause from ledger data.', icon:FolderCheck, color:'text-teal-400', bgColor:'bg-teal-500/20', badge:'Tax Audit', isNew:true },
  { id:'form29b', label:'Form 29B (MAT - 115JB)', subLabel:'Form 29B', description:'Audit Report for Minimum Alternate Tax u/s 115JB. Calculates book profit and MAT liability.', icon:FolderCheck, color:'text-teal-400', bgColor:'bg-teal-500/20', badge:'Tax Audit' },
  { id:'form3ceb', label:'Form 3CEB (Transfer Pricing)', subLabel:'Form 3CEB', description:'Transfer Pricing Audit Report u/s 92E. Reconciles transactions with foreign entities at arm length.', icon:FolderCheck, color:'text-teal-400', bgColor:'bg-teal-500/20', badge:'Tax Audit' },
  { id:'deferred-tax', label:'Deferred Tax & Dual Depreciation', subLabel:'AS-22 / DTA-DTL', description:'Dual depreciation schedules (Companies Act vs IT Act) + DTA/DTL balance sheet entries.', icon:BarChart3, color:'text-indigo-400', bgColor:'bg-indigo-500/20', badge:'Audit', isNew:true },
  { id:'form24q', label:'Form 24Q (Salary TDS Return)', subLabel:'Form 24Q', description:'Quarterly TDS return for salaries. Auto-generates from payroll register and employee PAN details.', icon:Receipt, color:'text-blue-400', bgColor:'bg-blue-500/20', badge:'TDS Return', isNew:true },
  { id:'form26q', label:'Form 26Q (Non-Salary TDS Return)', subLabel:'Form 26Q', description:'Quarterly TDS return for contractors, rent, professional fees u/s 194C/I/J. Auto-tracks thresholds.', icon:Receipt, color:'text-blue-400', bgColor:'bg-blue-500/20', badge:'TDS Return', isNew:true },
  { id:'form27q', label:'Form 27Q (Non-Resident TDS)', subLabel:'Form 27Q', description:'Quarterly TDS return on payments to Non-Residents. Computes DTAA treaty benefit rates automatically.', icon:Receipt, color:'text-blue-400', bgColor:'bg-blue-500/20', badge:'TDS Return' },
  { id:'form27eq', label:'Form 27EQ (TCS Quarterly Return)', subLabel:'Form 27EQ', description:'Quarterly statement of Tax Collected at Source on scrap, timber, motor cars, and minerals.', icon:Receipt, color:'text-cyan-400', bgColor:'bg-cyan-500/20', badge:'TCS Return' },
  { id:'form16', label:'Form 16 (Salary TDS Certificate)', subLabel:'Form 16', description:'Certificate of TDS deducted from employee salaries. Auto-generates Part A and Part B together.', icon:BadgeCheck, color:'text-green-400', bgColor:'bg-green-500/20', badge:'TDS Certificate' },
  { id:'form16a', label:'Form 16A (Vendor TDS Certificate)', subLabel:'Form 16A', description:'Certificate of TDS deducted from vendor/rent/professional payments. Quarterly auto-generation.', icon:BadgeCheck, color:'text-green-400', bgColor:'bg-green-500/20', badge:'TDS Certificate' },
  { id:'form16b', label:'Form 16B (Property TDS)', subLabel:'Form 16B', description:'TDS certificate u/s 194-IA for property purchase transactions above Rs 50 Lakhs.', icon:BadgeCheck, color:'text-green-400', bgColor:'bg-green-500/20', badge:'TDS Certificate' },
  { id:'form16c', label:'Form 16C (Rent TDS)', subLabel:'Form 16C', description:'TDS certificate u/s 194-IB for high monthly rent payments exceeding Rs 50,000 per month.', icon:BadgeCheck, color:'text-green-400', bgColor:'bg-green-500/20', badge:'TDS Certificate' },
  { id:'form16d', label:'Form 16D (Contractor TDS)', subLabel:'Form 16D', description:'TDS certificate u/s 194M for payments to contractors or professionals by individuals/HUF.', icon:BadgeCheck, color:'text-green-400', bgColor:'bg-green-500/20', badge:'TDS Certificate' },
  { id:'challan280', label:'Challan 280 (Income Tax Payment)', subLabel:'ITNS 280', description:'Depositing Self-Assessment, Advance Tax, and Regular Assessment taxes. Auto-fills from tax computation.', icon:CreditCard, color:'text-amber-400', bgColor:'bg-amber-500/20', badge:'Tax Challan', isNew:true },
  { id:'challan281', label:'Challan 281 (TDS/TCS Deposit)', subLabel:'ITNS 281', description:'Monthly challan to deposit TDS/TCS collected. Auto-initiates via bank API after CA approval.', icon:CreditCard, color:'text-amber-400', bgColor:'bg-amber-500/20', badge:'Tax Challan' },
  { id:'form26qb', label:'Form 26QB (Property TDS Challan)', subLabel:'Form 26QB', description:'Challan-cum-statement for TDS on purchase of land/property above Rs 50 Lakhs u/s 194-IA.', icon:CreditCard, color:'text-amber-400', bgColor:'bg-amber-500/20', badge:'TDS Challan' },
  { id:'form26qc', label:'Form 26QC (Rent TDS Challan)', subLabel:'Form 26QC', description:'Challan-cum-statement for TDS on high monthly rent (>Rs 50k/month) by individuals u/s 194-IB.', icon:CreditCard, color:'text-amber-400', bgColor:'bg-amber-500/20', badge:'TDS Challan' },
  { id:'form26qd', label:'Form 26QD (Contractor TDS Challan)', subLabel:'Form 26QD', description:'Challan-cum-statement for TDS u/s 194M on payments to contractors and professionals.', icon:CreditCard, color:'text-amber-400', bgColor:'bg-amber-500/20', badge:'TDS Challan' },
  { id:'form15ca', label:'Form 15CA (Foreign Remittance Declaration)', subLabel:'Form 15CA', description:'Online declaration u/s 195 before making foreign payments. Auto-checks DTAA treaty provisions.', icon:Globe, color:'text-rose-400', bgColor:'bg-rose-500/20', badge:'Foreign Payment' },
  { id:'form15cb', label:'Form 15CB (CA Foreign Payment Certificate)', subLabel:'Form 15CB', description:'CA certificate verifying tax deductions on foreign money transfers. Digitally signed with UDIN.', icon:Globe, color:'text-rose-400', bgColor:'bg-rose-500/20', badge:'Foreign Payment' },
  { id:'form67', label:'Form 67 (Foreign Tax Credit Claim)', subLabel:'Form 67', description:'Claiming Foreign Tax Credit for taxes paid abroad to avoid double taxation under DTAA.', icon:Globe, color:'text-rose-400', bgColor:'bg-rose-500/20', badge:'FTC Claim' },
  { id:'regime-optimizer', label:'Tax Regime Optimizer (Old vs New)', subLabel:'Regime Analysis', description:'Side-by-side Old vs New Regime comparison. Auto-calculates optimal regime and shows exact savings.', icon:TrendingUp, color:'text-violet-400', bgColor:'bg-violet-500/20', badge:'Income Tax', isNew:true },
  { id:'capital-gains', label:'Capital Gains Calculator (STCG/LTCG)', subLabel:'STCG/LTCG', description:'STCG/LTCG with CII indexation, Grandfathering clause (Jan 31 2018 FMV), and Sec 112A exemption.', icon:BarChart3, color:'text-emerald-400', bgColor:'bg-emerald-500/20', badge:'Income Tax', isNew:true },
  { id:'advance-tax-radar', label:'Advance Tax Radar (234B/C Predictor)', subLabel:'Advance Tax', description:'Projects full-year tax from YTD profit. Shows per-installment dues and interest risk u/s 234B/C.', icon:AlertTriangle, color:'text-cyan-400', bgColor:'bg-cyan-500/20', badge:'Income Tax', isNew:true },
  { id:'form35', label:'Form 35 (Appeal to CIT-Appeals)', subLabel:'Form 35', description:'Filing a first-level tax appeal before the Commissioner of Income Tax Appeals. AI drafts grounds.', icon:Scale, color:'text-orange-400', bgColor:'bg-orange-500/20', badge:'Litigation' },
  { id:'form36', label:'Form 36 (ITAT Appeal)', subLabel:'Form 36', description:'Filing second-level tax appeal before Income Tax Appellate Tribunal. AI finds precedents.', icon:Scale, color:'text-orange-400', bgColor:'bg-orange-500/20', badge:'Litigation' },
  { id:'notices', label:'Notice Tracker & AI Response Drafter', subLabel:'All Notices', description:'Auto-downloads IT/GST notices. AI finds matching evidence in Sannidh DB and drafts legal reply with case laws.', icon:AlertTriangle, color:'text-red-400', bgColor:'bg-red-500/20', badge:'Notices', isNew:true },
  { id:'form15gh', label:'Form 15G / 15H (No TDS Declarations)', subLabel:'Form 15G/H', description:'Declarations to receive interest income without TDS deduction. Validates eligibility automatically.', icon:ScrollText, color:'text-sky-400', bgColor:'bg-sky-500/20', badge:'Declaration' },
  { id:'form10ic', label:'Form 10-IC (22% Corporate Tax - 115BAA)', subLabel:'Form 10-IC', description:'Exercising option for corporate tax rate of 22% u/s 115BAA. One-time irrevocable filing.', icon:ScrollText, color:'text-sky-400', bgColor:'bg-sky-500/20', badge:'Declaration' },
  { id:'form10id', label:'Form 10-ID (15% New Mfg Tax - 115BAB)', subLabel:'Form 10-ID', description:'Exercising option for new manufacturing corporate tax rate of 15% u/s 115BAB.', icon:ScrollText, color:'text-sky-400', bgColor:'bg-sky-500/20', badge:'Declaration' }
];

export const INDIRECT_TAX: FormModuleMetadata[] = [
  { id:'gstr1', label:'GSTR-1 (Outward Sales Return)', subLabel:'GSTR-1', description:'Monthly/Quarterly return of outward sales invoices. Auto-compiles from Sannidh invoice ledger.', icon:Calculator, color:'text-green-400', bgColor:'bg-green-500/20', badge:'Regular Return' },
  { id:'gstr2b', label:'GSTR-2B (ITC Reconciliation)', subLabel:'GSTR-2B', description:'ITC matching: Download portal GSTR-2B and reconcile against Sannidh purchase register. Flags mismatches.', icon:GitCompare, color:'text-violet-400', bgColor:'bg-violet-500/20', badge:'ITC Matching', isNew:true },
  { id:'gstr3b', label:'GSTR-3B (Net Tax Payable Return)', subLabel:'GSTR-3B', description:'Monthly: Outward Tax minus ITC = Net Payable. DRC-01C alert if ITC exceeds 50% of output tax.', icon:IndianRupee, color:'text-blue-400', bgColor:'bg-blue-500/20', badge:'Regular Return' },
  { id:'gstr4', label:'GSTR-4 (Composition Annual Return)', subLabel:'GSTR-4', description:'Annual return for Composition Scheme taxpayers (up to Rs 1.5 Cr). Auto-calculates flat tax rate.', icon:FileText, color:'text-green-400', bgColor:'bg-green-500/20', badge:'Composition' },
  { id:'gstr5', label:'GSTR-5 (Non-Resident Taxable Person)', subLabel:'GSTR-5', description:'Monthly GST return for Non-Resident Foreign Taxable Persons. Tracks import transactions.', icon:Globe, color:'text-rose-400', bgColor:'bg-rose-500/20', badge:'Special Return' },
  { id:'gstr5a', label:'GSTR-5A (OIDAR / Digital Services)', subLabel:'GSTR-5A', description:'Monthly GST return for OIDAR service providers (foreign SaaS/digital services like Netflix, Zoom, AWS).', icon:Globe, color:'text-rose-400', bgColor:'bg-rose-500/20', badge:'Special Return' },
  { id:'gstr6', label:'GSTR-6 (Input Service Distributor)', subLabel:'GSTR-6', description:'Monthly return for Input Service Distributors (ISD). Distributes ITC credit to registered subsidiaries.', icon:ArrowLeftRight, color:'text-orange-400', bgColor:'bg-orange-500/20', badge:'ISD Return' },
  { id:'gstr7', label:'GSTR-7 (GST TDS Return)', subLabel:'GSTR-7', description:'Monthly return for GST TDS deductors (government bodies, notified entities). Reconciles deductions.', icon:Receipt, color:'text-cyan-400', bgColor:'bg-cyan-500/20', badge:'GST TDS' },
  { id:'gstr8', label:'GSTR-8 (E-Commerce TCS Return)', subLabel:'GSTR-8', description:'Monthly return for GST TCS by e-commerce operators (Amazon, Flipkart) on marketplace seller sales.', icon:Receipt, color:'text-cyan-400', bgColor:'bg-cyan-500/20', badge:'GST TCS' },
  { id:'gstr9', label:'GSTR-9 (GST Annual Return)', subLabel:'GSTR-9', description:'Annual return aggregating 12 months of GSTR-1 and GSTR-3B. Auto-compiles from Sannidh records.', icon:BookOpen, color:'text-amber-400', bgColor:'bg-amber-500/20', badge:'Annual Return' },
  { id:'gstr9c', label:'GSTR-9C (GST Reconciliation - CA Audit)', subLabel:'GSTR-9C', description:'CA-certified reconciliation of audited accounts vs GSTR-9 filing. Mandatory for turnover above Rs 5 Cr.', icon:GitCompare, color:'text-violet-400', bgColor:'bg-violet-500/20', badge:'Audit Statement' },
  { id:'gstr10', label:'GSTR-10 (Final Return on Cancellation)', subLabel:'GSTR-10', description:'Final GST return filed when cancelling GST registration. Clears final ITC balances with reversal.', icon:FileCheck, color:'text-red-400', bgColor:'bg-red-500/20', badge:'Closure Return' },
  { id:'gstr11', label:'GSTR-11 (UIN Holder Inward Supplies)', subLabel:'GSTR-11', description:'Inward supplies statement for UIN holders (foreign embassies, UN agencies) for GST refund claims.', icon:FileText, color:'text-sky-400', bgColor:'bg-sky-500/20', badge:'Special Return' },
  { id:'gst-cmp08', label:'CMP-08 (Composition Quarterly Payment)', subLabel:'CMP-08', description:'Quarterly tax payment statement for composition dealers. Auto-calculates from turnover register.', icon:CreditCard, color:'text-green-400', bgColor:'bg-green-500/20', badge:'Composition' },
  { id:'gst-drc03', label:'DRC-03 (Voluntary GST Payment)', subLabel:'DRC-03', description:'Voluntary tax payment to settle GST notices, GSTR-2B mismatches, or self-corrected errors.', icon:CreditCard, color:'text-amber-400', bgColor:'bg-amber-500/20', badge:'Tax Payment' },
  { id:'gst-pmt09', label:'PMT-09 (GST Ledger Head Transfer)', subLabel:'PMT-09', description:'Shift balances within GST tax cash ledger heads (CGST/SGST/IGST). Fixes wrong head deposits.', icon:ArrowLeftRight, color:'text-blue-400', bgColor:'bg-blue-500/20', badge:'Ledger Ops' },
  { id:'gst-rfd01', label:'RFD-01 (GST Refund Application)', subLabel:'RFD-01', description:'GST refund application for exports with zero-rated supply, inverted duty structure, or excess ITC.', icon:Banknote, color:'text-emerald-400', bgColor:'bg-emerald-500/20', badge:'GST Refund' },
  { id:'gst-reg01', label:'REG-01 (New GST Registration)', subLabel:'REG-01', description:'Application for fresh GST Registration for new businesses. Auto-populates from Sannidh business profile.', icon:UserCheck, color:'text-indigo-400', bgColor:'bg-indigo-500/20', badge:'Registration' },
  { id:'gst-reg16', label:'REG-16 (GST Cancellation)', subLabel:'REG-16', description:'Application for cancellation of GST Registration when business closes or falls below Rs 20 Lakh threshold.', icon:UserCheck, color:'text-red-400', bgColor:'bg-red-500/20', badge:'Cancellation' },
  { id:'gst-lut', label:'LUT (Export Without IGST Letter)', subLabel:'LUT', description:'Letter of Undertaking for export of goods/services without paying IGST. Annual filing with GSTIN.', icon:ScrollText, color:'text-teal-400', bgColor:'bg-teal-500/20', badge:'Export' },
  { id:'gst-apl01', label:'APL-01 (GST Appeal)', subLabel:'APL-01', description:'Filing appeals before the GST Appellate Authority against ex-parte orders. AI generates grounds.', icon:Scale, color:'text-orange-400', bgColor:'bg-orange-500/20', badge:'GST Appeal' },
  { id:'gst-import-export', label:'Customs & EXIM (ICEGATE Hub)', subLabel:'ICEGATE', description:'Bills of Entry tracking, IGST ITC reconciliation on imports, and Shipping Bills for export.', icon:Anchor, color:'text-indigo-400', bgColor:'bg-indigo-500/20', badge:'Customs', isNew:true }
];

export const CORPORATE_LAW: FormModuleMetadata[] = [
  { id:'aoc4', label:'Form AOC-4 (Annual Financials ROC)', subLabel:'AOC-4', description:'Filing audited Balance Sheet and P&L with the ROC. Auto-compiles from Sannidh Schedule III data.', icon:Building2, color:'text-emerald-400', bgColor:'bg-emerald-500/20', badge:'Annual ROC' },
  { id:'mgt7', label:'Form MGT-7 (Annual Return)', subLabel:'MGT-7', description:'Annual Return with shareholding pattern, directors, and debt details. Auto-populates from company registry.', icon:Building2, color:'text-emerald-400', bgColor:'bg-emerald-500/20', badge:'Annual ROC' },
  { id:'mgt15', label:'Form MGT-15 (AGM Report)', subLabel:'MGT-15', description:'Report on the Annual General Meeting filed with the ROC within 30 days of AGM date.', icon:Building2, color:'text-emerald-400', bgColor:'bg-emerald-500/20', badge:'Annual ROC' },
  { id:'dpt3', label:'Form DPT-3 (Deposits Return)', subLabel:'DPT-3', description:'Annual return of deposits and outstanding loans from directors and related parties.', icon:Building2, color:'text-emerald-400', bgColor:'bg-emerald-500/20', badge:'Annual ROC' },
  { id:'chg1', label:'Form CHG-1 (Create/Modify Charge)', subLabel:'CHG-1', description:'Creating or modifying a charge u/s 77 (bank loans against assets). 30-day deadline from execution.', icon:Lock, color:'text-yellow-400', bgColor:'bg-yellow-500/20', badge:'Charges' },
  { id:'chg4', label:'Form CHG-4 (Satisfy/Release Charge)', subLabel:'CHG-4', description:'Satisfaction of Charge (bank loan fully repaid). Removes lien on company assets from ROC records.', icon:Lock, color:'text-yellow-400', bgColor:'bg-yellow-500/20', badge:'Charges' },
  { id:'pas3', label:'Form PAS-3 (Share Allotment Return)', subLabel:'PAS-3', description:'Return of share allotment when raising equity funding. Must file within 30 days of allotment date.', icon:Layers, color:'text-cyan-400', bgColor:'bg-cyan-500/20', badge:'Share Capital' },
  { id:'sh7', label:'Form SH-7 (Authorized Capital Alteration)', subLabel:'SH-7', description:'Alteration/increase of authorized share capital. Requires board resolution and MGT-14 filing.', icon:Layers, color:'text-cyan-400', bgColor:'bg-cyan-500/20', badge:'Share Capital' },
  { id:'dir3kyc', label:'Form DIR-3 KYC (Annual Director KYC)', subLabel:'DIR-3 KYC', description:'Annual KYC of Director Identification Numbers. Tracks expiry. Prevents director disqualification.', icon:Fingerprint, color:'text-orange-400', bgColor:'bg-orange-500/20', badge:'Directors', isNew:true },
  { id:'dir12', label:'Form DIR-12 (Director Appointment/Removal)', subLabel:'DIR-12', description:'Appointment, changes, or resignation of directors. Must file within 30 days of change event.', icon:Fingerprint, color:'text-orange-400', bgColor:'bg-orange-500/20', badge:'Directors' },
  { id:'mbp1', label:'MBP-1 (Director Interest Disclosure)', subLabel:'MBP-1', description:'Director annual disclosure of interest in other entities u/s 184(1). Mandatory at every board meeting.', icon:Fingerprint, color:'text-orange-400', bgColor:'bg-orange-500/20', badge:'Directors' },
  { id:'dir8', label:'DIR-8 (Director Non-Disqualification)', subLabel:'DIR-8', description:'Director annual declaration of non-disqualification u/s 164(2). Filed at every AGM or board.', icon:Fingerprint, color:'text-orange-400', bgColor:'bg-orange-500/20', badge:'Directors' },
  { id:'msme1', label:'Form MSME-1 (45-Day MSME Dues Return)', subLabel:'MSME-1', description:'Half-yearly return of outstanding dues to MSME vendors beyond 45 days u/s 43B(h). Auto-scans payables.', icon:AlertTriangle, color:'text-red-400', bgColor:'bg-red-500/20', badge:'MSME', isNew:true },
  { id:'inc20a', label:'Form INC-20A (Business Commencement)', subLabel:'INC-20A', description:'Declaration of Commencement of Business within 180 days of incorporation. One-time mandatory filing.', icon:BadgeCheck, color:'text-green-400', bgColor:'bg-green-500/20', badge:'Compliance' },
  { id:'adt1', label:'Form ADT-1 (Auditor Appointment)', subLabel:'ADT-1', description:'Appointment of statutory auditors. Must file within 15 days of AGM. Links to UDIN workflow.', icon:UserCheck, color:'text-teal-400', bgColor:'bg-teal-500/20', badge:'Audit' },
  { id:'mgt14', label:'Form MGT-14 (Resolution Filing)', subLabel:'MGT-14', description:'Filing of special board and EGM resolutions u/s 179 with the ROC within 30 days.', icon:FileSignature, color:'text-purple-400', bgColor:'bg-purple-500/20', badge:'Resolutions' },
  { id:'financials', label:'Financial Statements (Schedule III)', subLabel:'B/S + P&L', description:'Balance Sheet (A=L+E validated), P&L with all margins, and Cash Flow statement. Full Schedule III.', icon:BarChart3, color:'text-yellow-400', bgColor:'bg-yellow-500/20', badge:'Accounts' },
  { id:'debtors', label:'Debtors Aging Analysis', subLabel:'Aging Report', description:'0-30/31-60/61-90/90+ day buckets. Auto 25%-50% provision. Recovery alerts and MSME cross-check.', icon:PieChart, color:'text-orange-400', bgColor:'bg-orange-500/20', badge:'Finance' },
  { id:'bank-rec-auto', label:'Bank Statement Auto-Recon AI', subLabel:'Bank Recon', description:'Upload PDF bank statements for automated parsing, AA feed matching, and suspense ledger analysis.', icon:Landmark, color:'text-teal-400', bgColor:'bg-teal-500/20', badge:'Finance', isNew:true },
  { id:'prof-cqc', label:'CA Quality & Compliance (ICAI/UDIN)', subLabel:'ICAI SQC-1', description:'CPE Hours tracker, UDIN prefill, Indemnity Insurance tracking, and Audit Peer Review prep (SQC-1).', icon:Sparkles, color:'text-pink-400', bgColor:'bg-pink-500/20', badge:'Firm Quality', isNew:true },
  { id:'invoice', label:'Invoice Parser & OCR Engine', subLabel:'Invoice OCR', description:'OCR invoice upload (Textract-ready) + DIN/TAN expiry tracker with DIR-3 KYC alerts and GL mapping.', icon:ScanLine, color:'text-pink-400', bgColor:'bg-pink-500/20', badge:'Tools', isNew:true }
];

export const LABOR_LAWS: FormModuleMetadata[] = [
  { id:'epf-ecr', label:'EPFO ECR (Monthly PF Challan-cum-Return)', subLabel:'ECR', description:'Monthly Electronic Challan-cum-Return for employee Provident Fund contributions. Auto-compiles from payroll.', icon:Users, color:'text-cyan-400', bgColor:'bg-cyan-500/20', badge:'Provident Fund', isNew:true },
  { id:'pf12a', label:'PF Form 12A (Monthly Recovery Statement)', subLabel:'Form 12A', description:'Monthly statement of PF recoveries from employee wages and employer contributions summary.', icon:Users, color:'text-cyan-400', bgColor:'bg-cyan-500/20', badge:'Provident Fund' },
  { id:'pf5-10', label:'PF Form 5 & 10 (Joiners and Leavers)', subLabel:'Form 5/10', description:'Monthly returns for new employees joining (Form 5) and exiting (Form 10) the organization.', icon:Users, color:'text-cyan-400', bgColor:'bg-cyan-500/20', badge:'Provident Fund' },
  { id:'pf11', label:'PF Form 11 (Employee PF Declaration)', subLabel:'Form 11', description:'Declaration filled by new employees upon joining for PF membership and nomination activation.', icon:ClipboardList, color:'text-cyan-400', bgColor:'bg-cyan-500/20', badge:'Provident Fund' },
  { id:'esic-return', label:'ESIC Monthly Contribution Return', subLabel:'ESIC Return', description:'Monthly return of ESI contributions. 4.25% employer plus 0.75% employee on wages up to Rs 21,000.', icon:HeartHandshake, color:'text-rose-400', bgColor:'bg-rose-500/20', badge:'ESI' },
  { id:'esic-form1', label:'ESIC Form 1 (Employee Health Card)', subLabel:'ESIC Form 1', description:'Declaration form for new employee health card registration under the ESI Act 1948.', icon:HeartHandshake, color:'text-rose-400', bgColor:'bg-rose-500/20', badge:'ESI' },
  { id:'salary-tds', label:'Salary Payroll & TDS (Form 16/24Q)', subLabel:'Payroll TDS', description:'Full payroll processing: salary computation, Form 16 auto-generation, and quarterly 24Q/26Q filing.', icon:FileText, color:'text-blue-400', bgColor:'bg-blue-500/20', badge:'Payroll', isNew:true },
  { id:'gratuity', label:'Gratuity Calculator (Payment of Gratuity Act)', subLabel:'Gratuity', description:'Auto-computes gratuity for employees with 5+ years service. Applies Sec 10(10) exemption limit.', icon:DollarSign, color:'text-green-400', bgColor:'bg-green-500/20', badge:'Gratuity', isNew:true },
  { id:'pt-return', label:'Professional Tax (State-wise PT Returns)', subLabel:'PT Return', description:'Monthly/Annual Professional Tax returns across all 29 state-specific slab rates. Auto-deduction engine.', icon:FileCog, color:'text-amber-400', bgColor:'bg-amber-500/20', badge:'Prof Tax' },
  { id:'board-meetings', label:'Corporate Governance Suite (Board/AGM/EGM)', subLabel:'Corp Gov', description:'Board meeting scheduler, 8 resolution templates, AGM 21-day notice workflow, and secretarial calendar.', icon:Calendar, color:'text-indigo-400', bgColor:'bg-indigo-500/20', badge:'Governance', isNew:true }
];

export const FEMA_RBI: FormModuleMetadata[] = [
  { id:'fc-gpr', label:'Form FC-GPR (FDI Inflow Reporting)', subLabel:'FC-GPR', description:'Reporting FDI inflows to RBI within 30 days of share allotment. Auto-maps FIRC with allotment data.', icon:Globe, color:'text-emerald-400', bgColor:'bg-emerald-500/20', badge:'FDI Inbound' },
  { id:'fc-trs', label:'Form FC-TRS (Share Transfer Reporting)', subLabel:'FC-TRS', description:'Reporting transfer of shares between resident and non-resident. Validates arm length pricing.', icon:ArrowLeftRight, color:'text-emerald-400', bgColor:'bg-emerald-500/20', badge:'FDI Transfer' },
  { id:'fla', label:'Form FLA (Foreign Liabilities and Assets)', subLabel:'FLA Annual', description:'Annual RBI return of Foreign Liabilities and Assets due July 15. Auto-extracts from Sannidh balance sheet.', icon:Globe, color:'text-blue-400', bgColor:'bg-blue-500/20', badge:'Annual RBI' },
  { id:'odi', label:'Form ODI (Overseas Direct Investment)', subLabel:'ODI', description:'Reporting Overseas Direct Investment for JVs/WOS abroad. Tracks remittances and annual returns.', icon:Globe, color:'text-purple-400', bgColor:'bg-purple-500/20', badge:'ODI Outbound' },
  { id:'fema-sebi', label:'RBI, FEMA & SEBI Compliance Hub', subLabel:'FEMA/SEBI', description:'FDI/ODI processing, Export Realization tracking (EDPMS), LODR Compliance Tracker, Insider Trading DB.', icon:Shield, color:'text-emerald-400', bgColor:'bg-emerald-500/20', badge:'Apex Regulatory', isNew:true },
  { id:'accounting-sync', label:'Historical Data Migration & ERP Bridge', subLabel:'Data Import', description:'One-time historical migration of past ledger data from legacy ERP systems into Sannidh native database.', icon:Database, color:'text-zinc-400', bgColor:'bg-zinc-500/20', badge:'Data Ops', isNew:true }
];
