import { ArrowLeft, AlertTriangle, Shield, Scale } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { Button } from "@/components/ui/button";

const Disclaimers = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background">
      <div className="container mx-auto px-4 py-8 max-w-4xl">
        <Button
          variant="ghost"
          onClick={() => navigate(-1)}
          className="mb-6"
        >
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back
        </Button>

        <div className="bg-card border rounded-lg p-8">
          <h1 className="text-3xl font-bold mb-2">Legal Disclaimers</h1>
          <p className="text-muted-foreground mb-8">
            Last Updated: {new Date().toLocaleDateString()}
          </p>

          <div className="prose prose-slate dark:prose-invert max-w-none space-y-6">
            {/* General Disclaimer */}
            <section className="bg-red-500/10 border border-red-500/20 rounded-lg p-6">
              <div className="flex items-start gap-3">
                <AlertTriangle className="h-6 w-6 text-red-500 mt-1 flex-shrink-0" />
                <div>
                  <h2 className="text-2xl font-semibold mb-4 text-red-600 dark:text-red-400">
                    General Disclaimer
                  </h2>
                  <p className="text-muted-foreground">
                    <strong>IMPORTANT:</strong> The information, tools, and services provided by REGULON are for 
                    informational and educational purposes only. REGULON is NOT a substitute for professional legal, 
                    financial, tax, or compliance advice from qualified professionals.
                  </p>
                </div>
              </div>
            </section>

            {/* Legal Advisory Disclaimer */}
            <section>
              <div className="flex items-start gap-3 mb-4">
                <Scale className="h-6 w-6 text-blue-500 mt-1 flex-shrink-0" />
                <h2 className="text-2xl font-semibold">Legal Advisory Disclaimer</h2>
              </div>
              
              <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-4">
                <p className="text-yellow-700 dark:text-yellow-500 font-semibold mb-3">
                  NOT LEGAL ADVICE
                </p>
                <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
                  <li>REGULON does not provide legal advice or legal representation</li>
                  <li>The platform does not create an attorney-client relationship</li>
                  <li>Content generated by AI tools should be reviewed by qualified legal professionals</li>
                  <li>Regulatory information may not be exhaustive or up-to-date in all cases</li>
                  <li>Users should consult licensed attorneys for specific legal matters</li>
                  <li>REGULON is not responsible for decisions made based on platform content</li>
                </ul>
              </div>

              <p className="text-muted-foreground mt-4">
                <strong>Recommendation:</strong> Always verify regulatory updates and compliance requirements with 
                qualified legal counsel before taking action.
              </p>
            </section>

            {/* Financial Advisory Disclaimer */}
            <section>
              <div className="flex items-start gap-3 mb-4">
                <Shield className="h-6 w-6 text-green-500 mt-1 flex-shrink-0" />
                <h2 className="text-2xl font-semibold">Financial & Tax Advisory Disclaimer</h2>
              </div>
              
              <div className="bg-yellow-500/10 border border-yellow-500/20 rounded-lg p-4">
                <p className="text-yellow-700 dark:text-yellow-500 font-semibold mb-3">
                  NOT FINANCIAL OR TAX ADVICE
                </p>
                <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
                  <li>REGULON does not provide financial, investment, or tax advice</li>
                  <li>The platform is not registered with SEBI, RBI, or other financial regulatory authorities</li>
                  <li>Financial and tax information is for general awareness only</li>
                  <li>Users should consult Chartered Accountants (CA) or tax professionals for specific advice</li>
                  <li>Compliance tools do not guarantee tax savings or financial outcomes</li>
                  <li>REGULON is not liable for financial decisions made using platform information</li>
                </ul>
              </div>

              <p className="text-muted-foreground mt-4">
                <strong>Recommendation:</strong> Consult with licensed Chartered Accountants, financial advisors, 
                or tax consultants for personalized financial and tax guidance.
              </p>
            </section>

            {/* AI-Generated Content Disclaimer */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">AI-Generated Content Disclaimer</h2>
              <p className="text-muted-foreground mb-4">
                REGULON uses artificial intelligence (AI) and machine learning technologies to assist with compliance 
                tasks, including:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
                <li>Document drafting and review</li>
                <li>Compliance recommendations</li>
                <li>Regulatory update summaries</li>
                <li>Chatbot responses</li>
              </ul>
              
              <div className="bg-orange-500/10 border border-orange-500/20 rounded-lg p-4 mt-4">
                <p className="text-orange-700 dark:text-orange-500 font-semibold mb-2">
                  Important Limitations:
                </p>
                <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
                  <li>AI-generated content may contain errors, omissions, or inaccuracies</li>
                  <li>AI does not replace human judgment and professional expertise</li>
                  <li>All AI-generated documents must be reviewed and verified by qualified professionals</li>
                  <li>REGULON is not responsible for errors in AI-generated content</li>
                  <li>Users are solely responsible for final compliance decisions</li>
                </ul>
              </div>
            </section>

            {/* Data Accuracy Disclaimer */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">Data Accuracy Disclaimer</h2>
              <p className="text-muted-foreground">
                While REGULON strives to provide accurate and timely regulatory information:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4 mt-4">
                <li>Regulatory data is sourced from public government websites and may have delays</li>
                <li>We cannot guarantee 100% accuracy, completeness, or timeliness of all information</li>
                <li>Users should verify critical information directly with official government sources</li>
                <li>REGULON is not liable for decisions based on outdated or incorrect data</li>
              </ul>
            </section>

            {/* No Warranty Disclaimer */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">No Warranty</h2>
              <p className="text-muted-foreground">
                THE PLATFORM IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR 
                IMPLIED, INCLUDING BUT NOT LIMITED TO:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4 mt-4">
                <li>Warranties of merchantability or fitness for a particular purpose</li>
                <li>Warranties of non-infringement</li>
                <li>Warranties regarding accuracy, reliability, or availability</li>
                <li>Warranties that the platform will be error-free or uninterrupted</li>
              </ul>
            </section>

            {/* Limitation of Liability */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">Limitation of Liability</h2>
              <div className="bg-red-500/10 border border-red-500/20 rounded-lg p-4">
                <p className="text-muted-foreground">
                  TO THE MAXIMUM EXTENT PERMITTED BY LAW, REGULON, ITS OFFICERS, DIRECTORS, EMPLOYEES, AND AFFILIATES 
                  SHALL NOT BE LIABLE FOR:
                </p>
                <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4 mt-4">
                  <li>Any regulatory penalties or fines resulting from non-compliance</li>
                  <li>Financial losses or business damages</li>
                  <li>Errors in AI-generated content or recommendations</li>
                  <li>Data breaches or unauthorized access (beyond reasonable security measures)</li>
                  <li>Third-party actions or government decisions</li>
                  <li>Indirect, consequential, or punitive damages</li>
                </ul>
              </div>
            </section>

            {/* India-Specific Disclaimer */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">India-Specific Regulatory Disclaimer</h2>
              <p className="text-muted-foreground mb-4">
                REGULON provides information related to Indian regulatory bodies including:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
                <li>Ministry of Corporate Affairs (MCA) - Companies Act 2013</li>
                <li>Securities and Exchange Board of India (SEBI)</li>
                <li>Reserve Bank of India (RBI)</li>
                <li>Goods and Services Tax Network (GSTN)</li>
                <li>Income Tax Department</li>
                <li>Central Board of Indirect Taxes and Customs (CBIC)</li>
              </ul>
              <p className="text-muted-foreground mt-4">
                <strong>Important:</strong> REGULON is not affiliated with, endorsed by, or authorized by any Indian 
                government authority or regulatory body. Users must independently verify all compliance requirements 
                with the respective authorities.
              </p>
            </section>

            {/* User Responsibility */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">User Responsibility</h2>
              <p className="text-muted-foreground mb-4">
                By using REGULON, you acknowledge and agree that:
              </p>
              <ul className="list-disc list-inside text-muted-foreground space-y-2 ml-4">
                <li>You are solely responsible for your compliance decisions</li>
                <li>You will verify all information with qualified professionals</li>
                <li>You understand the platform is a tool, not a replacement for professional advice</li>
                <li>You will not rely solely on AI-generated content for critical decisions</li>
                <li>You accept full liability for actions taken based on platform information</li>
              </ul>
            </section>

            {/* Contact for Legal Matters */}
            <section>
              <h2 className="text-2xl font-semibold mb-4">Contact for Legal Matters</h2>
              <p className="text-muted-foreground mb-4">
                For questions about these disclaimers or legal matters, contact:
              </p>
              <div className="bg-muted/50 rounded-lg p-4">
                <p className="text-sm font-mono">Email: legal@regulon.ai</p>
                <p className="text-sm font-mono">Website: www.regulon.ai</p>
              </div>
            </section>

            <div className="bg-blue-500/10 border border-blue-500/20 rounded-lg p-4 mt-8">
              <p className="text-sm text-blue-600 dark:text-blue-400">
                <strong>Note:</strong> This is a placeholder document. The final Disclaimers will be prepared by 
                our legal team and will include additional provisions as required by Indian and international law.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Disclaimers;
