// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

const hasSupabaseEnv = Boolean(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
const fallbackUrl = "https://placeholder.supabase.co";
const fallbackKey = "public-anon-key-placeholder";

if (!hasSupabaseEnv) {
  // Keep UI routes functional in environments where env vars are not configured yet.
  console.warn(
    "[REGULON] Missing VITE_SUPABASE_URL or VITE_SUPABASE_PUBLISHABLE_KEY. Supabase calls will fail until configured."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  hasSupabaseEnv ? SUPABASE_URL : fallbackUrl,
  hasSupabaseEnv ? SUPABASE_PUBLISHABLE_KEY : fallbackKey,
  {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
